{{- if .Values.ingress.enabled -}}
{{/* Define service names for ingress - same logic as deployment */}}
{{- $serviceName := include "kubernetes-service.fullname" . -}}
{{- $activeServiceName := $serviceName -}}

{{/* Override service names based on configuration */}}
{{- if or .Values.rollout.blueGreen.enabled .Values.rollout.canary.enabled -}}
  {{- if .Values.rollout.blueGreen.activeService -}}
    {{/* Use explicitly defined active service name from blueGreen config */}}
    {{- $activeServiceName = .Values.rollout.blueGreen.activeService -}}
  {{- else if .Values.rollout.canary.activeService -}}
    {{/* Use explicitly defined active service name from canary config */}}
    {{- $activeServiceName = .Values.rollout.canary.activeService -}}
  {{- else if not .Values.rollout.useBaseServiceName -}}
    {{/* Default behavior: add -active suffix */}}
    {{- $activeServiceName = printf "%s-active" $serviceName -}}
  {{- end -}}
{{- end -}}

{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "kubernetes-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "kubernetes-service.labels" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $activeServiceName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $activeServiceName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}