{{- if .Values.disruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-{{ include "helm.name" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.disruptionBudget.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm.name" . }}
{{- end }}