{{- if .Values.disruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubernetes-service.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-service.labels" . | nindent 4 }}
{{- with .Values.disruptionBudget.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubernetes-service.fullname" . }}
{{- end }}
