{{- if .Values.disruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubernetes-service.name" . }}-pdb
  namespace: {{ .Release.Namespace }}
{{- with .Values.disruptionBudget.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
  selector:
    matchLabels:
      {{- if or ( default .Values.rollout.blueGreen.enabled false ) ( default .Values.rollout.canary.enabled false ) }}
      app.kubernetes.io/name: {{ include "kubernetes-service.fullname" . }}-active
      {{- else }}
      app.kubernetes.io/name: {{ include "kubernetes-service.fullname" . }}
      {{- end }}
{{- end }}