name: Get GitHub Helm chart updates and publish them for consumption

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**.md'
      - '**/CODEOWNERS'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gitleaks cache
        id: cache-gitleaks
        uses: actions/cache@v3
        with:
          path: /tmp/gitleaks
          key: ${{ runner.os }}-gitleaks-${GITLEAKS_VERSION}
          restore-keys: |
            ${{ runner.os }}-gitleaks-${GITLEAKS_VERSION}
            ${{ runner.os }}-gitleaks-

      - name: Download GitLeaks
        if: ${{ steps.cache-gitleaks.outputs.cache-hit != 'true' }}
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
          mkdir /tmp/gitleaks
          tar -xf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz -C /tmp/gitleaks

      - name: Run GitLeaks check
        run: /tmp/gitleaks/gitleaks detect --verbose

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Installation
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"